### ISSUE TITLE
Add parameter matching

### ISSUE THREAD

**Issue by s-taylor** [MadRabbit/graphql-mock#10]
Currently the mocks you setup do not consider the parameters provided, and return the mocked result regardless. It would be great to be able to define the parameters expected and if they do not match do not return the mocked result.

This would enable mocking the same query and having it return different results when different parameters are received which currently is not possible.

**Comment by kaievns** [comment]
ok, this is a thing since v1.0 now:

```js
mock.expect({ query, variables: { a: 1 } }).reply(oneResponse);
mock.expect({ query, variables: { b: 2 } }).reply(anotherResponse);
mock.expect({ query, variables: { c: 3 } }).fail('this is terrible');
```

**Comment by s-taylor** [comment]
Awesome!
