### ISSUE TITLE
Test with graphql client directly? (Without React component wrappers)

### ISSUE THREAD

**Issue by pachuka** [MadRabbit/graphql-mock#13]
Hi, first off thanks for providing this library, it is super useful!

I am trying to mock the apollo-graphql client when calling mutate/queries on the client object directly.

This seems to mostly be working, but it seems like the then/catch is never being resolved. Any thoughts? I am not 100% sure that I am initializing everything that is necessary for properly setting up the mocking, but especially when using mutate to create new data, I assume this should work.

I am creating the mock client as follows:
```js
import { addMockFunctionsToSchema } from 'graphql-tools';
import GraphQLMock from 'graphql-mock';
import { buildClientSchema, GraphQLScalarType, Kind } from 'graphql';
const introspectionResult = require('../schema');

addMockFunctionsToSchema({
  schema,
  preserveResolvers: true
});

const graphqlMock = new GraphQLMock(
  schema,
  {
    DateTime: () => {
      return new Date();
    }
  },
  {
    DateTime: new GraphQLScalarType({
      name: 'DateTime',
      description: 'DateTime custom scalar type',
      parseValue(value) {
        return new Date(value); // value from the client
      },
      serialize(value) {
        return value.getTime(); // value sent to the client
      },
      parseLiteral(ast) {
        if (ast.kind === Kind.INT) {
          return parseInt(ast.value, 10); // ast value is always in string format
        }
        return null;
      }
    })
  }
);
const epicMiddleware = createEpicMiddleware(contactEpics, { dependencies: { client: graphqlMock.client } });
const mockStore = configureMockStore([epicMiddleware]);

```

Usage:
```js
const createAsyncEpic = <P1, P2, P3>(
  actions: { request: any; success: any; failure: any },
  mutation: any,
  isProtected: boolean = false
) => {
  const epic: Epic<RootAction, RootState> = (action$, state$, { client }) =>
    action$.pipe(
      filter(isActionOf(actions.request)),
      withLatestFrom(state$),
      mergeMap(([action, state]) => {
        return client
          .mutate({ mutation, variables: { ...(action as any).payload } })
          .then((result: ApolloQueryResult<P2>) => {
            console.log('hello world');
            console.log(`success: ${JSON.stringify(result.data)}`);
            return actions.success(result.data);
          })
          .catch((error: ApolloError) => {
            console.log(`failure: ${JSON.stringify(error)}`);
            return actions.failure(error.graphQLErrors[0].message);
          });
      })
    );
 
  return epic;
};
```

I guess I am really just using this mock client as the "server" per say, maybe this is the wrong way to go about what I am trying to test.

**Comment by kaievns** [comment]
Hi Piyush,

I don't not seem to be familiar with the setup you're using, we're mostly straight up react users. so, i might not be super useful in this case. But, I can point you towards the thing that might be causing the problem.

graphql-mock uses a stubbed promises thing. it sort of looks like a Promise but it resolves/rejects right away in the same tick. the point being is that you wouldn't need to mess with async/await in your tests, the mocked state would be available immediately. https://github.com/MadRabbit/graphql-mock/blob/master/src/client.ts#L11-L58

unfortunately those stubbed promises are quite simplistic, and not meant to be used in deeply chained then/catch calls. it works fine in `react-apollo`, but it might be throwing some curved balls into whatever thing you're using.

**Comment by pachuka** [comment]
Aha, got it. I think I am going about this the wrong way in general. I think I really just case about the output of the query, so maybe I just need a local/mock graphql server rather than client for my tests. Maybe apollo-link-schema without the immediately resolving promises is what I am really after... 

My setup is using redux-observable for handling dispatching async calls and I am directly accessing the apollo-client within my epics for that and when it returns success or failure I dispatch another action. I think I am running into issues where I need to mock the async nature of the action dispatching as well as the graphql server since in the test it won't have access to the real one.

Thanks for the help, I'll close this for now.
