### ISSUE TITLE
No way of passing custom resolvers to makeExecutableSchema

### ISSUE THREAD

**Issue by d4rky-pl** [MadRabbit/graphql-mock#3]
There is no way to pass custom resolver to `makeExecutableSchema`.
I needed it because [I have this exact problem](https://github.com/graphql/graphql-js/issues/497#issuecomment-248766432)

More specifically: I get `GraphQL error: No mock defined for type "DateTime"` and `GraphQL error: Expected a value of type "DateTime" but received: Mon Apr 16 2018 13:30:47 GMT+0200 (CEST)` and I figured I need to replace the resolver to fix it.

**Comment by kaievns** [comment]
have you tried to pass the `mocks` param? https://github.com/MadRabbit/graphql-mock/blob/master/src/client.ts#L6-L9

**Comment by d4rky-pl** [comment]
Yes, this is a different problem. If you have custom scalars (like DateTime in our case) then there's no way of passing information about how they should be handled.

I've modified the library locally to add the ability to pass the resolvers and it worked correctly.

**Comment by kaievns** [comment]
would you kindly show me an example what you've done, so i could add it to the lib?

**Comment by d4rky-pl** [comment]
Just added third parameter (`resolvers`) to `MockClient` that I then passed to `makeExecutableSchema`. 

Then I could do this:

```javascript
const resolvers = {
  DateTime: {
    __parseValue(value) {
      return new Date(value); // value from the client
    },
    __serialize(value) {
      return value.getTime(); // value sent to the client
    },
    __parseLiteral(ast) {
      if (ast.kind === Kind.INT) {
        return parseInt(ast.value, 10); // ast value is always in string format
      }
      return null;
    }
  },
}

export default new GraphQLMock(schema, mocks, resolvers);
```

**Comment by kaievns** [comment]
ah, that's pretty easy, let me quickly drill a hole for that in the interface

**Comment by kaievns** [comment]
could give `v0.2.0` a go? i've added some features in there for you https://github.com/MadRabbit/graphql-mock/commit/e0a015036b552d18b12cefac68bf384ec62d8edb

**Comment by d4rky-pl** [comment]
README, line 109, you forgot to add resolvers to the example :)
Other than that, looks great 👍

**Comment by wesbos** [comment]
I PR'd this https://github.com/MadRabbit/graphql-mock/pulls

This is good to close, though 0.2.0 doesn't include these changes on npm
