### ISSUE TITLE
How do I trigger loading and error states?

### ISSUE THREAD

**Issue by wesbos** [MadRabbit/graphql-mock#4]
Thanks for the great library - I'm looking to test my loading and error states - how would I trigger these states with this library?

**Comment by kaievns** [comment]
Hey Wes, at the moment i don't have that. but let me figure something out quickly

**Comment by wesbos** [comment]
Fantastic - thank you!

**Comment by kaievns** [comment]
hey, so i've just published `0.1.0`, which has this https://github.com/MadRabbit/graphql-mock#testing-error-states

could you give a go and let me know how did it go? thanks!

**Comment by kaievns** [comment]
here is an example that i used https://github.com/MadRabbit/graphql-mock/blob/master/test/index_test.tsx#L63-L70

**Comment by wesbos** [comment]
Hey @MadRabbit thank you so much! I'm more looking to test the error states in my UI, not the data since I'm using the <Query> component - I'd like to be able to flip them on/off. Not  sure if this is out of the scope of your module or not though

**Comment by kaievns** [comment]
hey, could you maybe post me an example what you're trying to test and how would you like it to look like? thanks!

**Comment by wesbos** [comment]
So I am created a mocked client:

```
const mocked = new MockClient(schema, mocks);
```

Then when I test my components, I wrap them in `<ApolloProvider>` and exposed the mocked client to the component. 

This is perfect for components that are wrapped in a query:

```js
const SingleItem = props => (
  <Query query={SINGLE_ITEM_QUERY} variables={{ id: props.id }}>
    {({ data: { items }, loading, error }) => {
      if (error) return <p>Error!</p>;
      const [item] = items;
      return (
        <SingleItemStyles data-test="SingleItem">
          <Error error={error} />
          <img src={item.largeImage || item.image} alt={item.title} />
          <div className="details">
            <h2>Viewing {item.title}</h2>
            <p>{item.description}</p>
            <Link
              href={{
                pathname: '/admin/update',
                query: { id: item.id },
              }}
            >
              <a>Edit ✏️</a>
            </Link>
          </div>
        </SingleItemStyles>
      );
    }}
  </Query>
);
```

but I'm wonder how do I test my error and loading states? 

I've found out I can test the Loading state by immediately checking the component after it mounts, but I'm not sure how to trigger an error state

**Comment by kaievns** [comment]
hey @wesbos, so i've added couple of examples of the `Query` component tests

https://github.com/MadRabbit/graphql-mock/blob/master/test/index_test.tsx#L78-L102

let me know if you have questions

**Comment by kaievns** [comment]
closing this as the was no action for a bit
