### ISSUE TITLE
Possible to check for mutations as well?

### ISSUE THREAD

**Issue by wesbos** [MadRabbit/graphql-mock#5]
Is is possible to also check if mutations were called with this library? Or just queries?

**Comment by wesbos** [comment]
I think this answer to this is no - finding other ways to test mutations

**Comment by kaievns** [comment]
yeah you will, it's a bit WIP at the moment, hold on tight

**Comment by wesbos** [comment]
Awesome!

**Comment by kaievns** [comment]
hey @wesbos so i've just published 0.4.0, which has this inside https://github.com/MadRabbit/graphql-mock/blob/master/test/index_test.tsx#L161-L225

would you kindly give a try and let me know how did it go?

**Comment by kaievns** [comment]
closing due to lack of action
