### ISSUE TITLE
Pass in custom client?

### ISSUE THREAD

**Issue by wesbos** [MadRabbit/graphql-mock#6]
Apologies for all the issues I'm opening, but I think this package is severely needed right now :) 

What do you think about passing in our own apollo client config? I'm asking because I'm using apollo boost which has the local state link, and the one you are using doesn't include that.

**Comment by kaievns** [comment]
no drama at all! actually, i appreciate all the ideas you're throwing in here :)

How do you like this? https://github.com/MadRabbit/graphql-mock#using-existing-apolloclient i've just published `0.3.0` which should work with your own clients

**Comment by wesbos** [comment]
This is great -thank you. I'm just realizing that I can't use it with Apollo Boost because that requires a URL and in my tests I need to pass typeDefs

**Comment by wesbos** [comment]
Closing it as you have implemented it
