### ISSUE TITLE
npm 0.2.0 doesn't match github

### ISSUE THREAD

**Issue by wesbos** [MadRabbit/graphql-mock#8]
I think when you published 0.2.0 this commit didn't make it:

https://github.com/MadRabbit/graphql-mock/commit/e0a015036b552d18b12cefac68bf384ec62d8edb

https://unpkg.com/graphql-mock@0.2.0/dist/client.ts

Could you re-pull and re-publish? Thank you : )

**Comment by kaievns** [comment]
that's bizarre, could you please try 0.2.1 for me?

**Comment by wesbos** [comment]
that did it -thanks!
