### ISSUE TITLE
Explode when un-mocked query/mutation occurs

### ISSUE THREAD

**Issue by s-taylor** [MadRabbit/graphql-mock#9]
Similar to how Nock functions, it would be great if graphql-mock would throw an exception when an un-mocked query or mutation is passed. This would give visibility of when something is not mocked correctly.

Similarly, it would also be nice to add an `.isDone()` method to use to assert that all mocks that have been setup have been executed.

**Comment by kaievns** [comment]
from v1.0, now it will explode by default if an unmocked query or mutation will try to get through.

it can be disabled where needed too https://github.com/MadRabbit/graphql-mock/blob/master/test/index_test.tsx#L22-L29
